### ISSUE TITLE
Change preview icon from visibility to preview

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE-Client#1045]
Change in all places in the Authoring Tool and Classroom Monitor.

**Comment by hirokiterashima** [comment]
@geoffreykwan and @breity:

Should the preview icon be ```<mat-icon>tv</mat-icon>``` like we have now in run settings menu item:
<img width="274" alt="Screenshot 2023-10-23 at 12 11 25 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/44e89ab0-4bf6-4dfb-b768-82b7d268afba">

Or, ```<mat-icon>preview</mat-icon>```, which would look like this:
<img width="669" alt="Screenshot 2023-10-23 at 12 12 37 PM" src="https://github.com/WISE-Community/WISE-Client/assets/119416/c8ee04fa-2167-480d-8998-d4cbeb7de4b6">

Either way, we should make them consistent across AT, CM, and site?

**Comment by hirokiterashima** [comment]
We decided to use the ```<mat-icon>preview</mat-icon>```
