### ISSUE TITLE
feat(Graph): Show specific column value in point tooltip

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE-Client#1121]
## Description
In Graph components, allow authors to specify a column to show the value of for the tooltip label when mousing over a point in the graph.

For example, instead of showing the series name in this graph (% in poverty) at the top of the tooltip, show the corresponding value for the "County" column (e.g. "San Diego"):

![Image](https://user-images.githubusercontent.com/297450/226522956-80ed01fe-2058-4fae-aeb3-eab07399ab78.png)

**Comment by geoffreykwan** [comment]
Duplicate of #1142
