### ISSUE TITLE
bug(Manage Students): Drag student to workgroup puts wrong student into workgroup

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE-Client#1219]
1. Create a run
2. Have 4 student accounts add the run but do not click "Launch". For example aa0101, bb0101, cc0101, dd0101.
3. Go to the Manage Students view for the run. You should see 4 students in the "Students without a team".
4. Click "New Team" and then add the first student aa0101 and click "Create".
5. Choose a student that is not the first student in "Students without a team". In my case bb0101 is the first student in my "Students without a team" so I will choose cc0101 or dd0101.
- If I drag cc0101 into the team and click "Proceed", it will add dd0101 to the team instead
- If I drag dd0101 into the team and click "Proceed", it will add cc0101 to the team instead
- If I drag bb0101 into the team and click "Proceed", it will add bb0101 to the team correctly

**Comment by hirokiterashima** [comment]
Hmm. I can't reproduce this. I tried it three time locally. Are there any other special setup/steps needed?
