### ISSUE TITLE
style(Node Authoring): Collapse top UI elements

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Client#1351]
## Description
The top hover area is now pretty tall and takes up quite a bit of vertical space when you scroll down. Consolidate all the UI elements up there into two rows. For example, the top row could contain the back button, advanced button, undo button, icon button, step title input, preview button. The second row could contain the Components label, add component button, expand all button, collapse all button.

**Comment by breity** [comment]
Closed by #1357.
