### ISSUE TITLE
feat(Classroom Monitor): Sort by first and last names in Grade by Team

### ISSUE THREAD

**Issue by breity** [WISE-Community/WISE-Client#1599]
## Description

- Show one row per student instead of one row per workgroup (team).
- Remove the Student Names column and replace with two columns: First Name, Last Name. This will allow teachers to sort by first name or last name, as well as by team number.
- Rename Grade by Team view to Grade by Student.

**Comment by hirokiterashima** [comment]
addressed in #1620
