### ISSUE TITLE
Rewrite Manage Students in Angular

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Client#17]
Right now  Classroom Monitor > Manage Student is embedding the legacy viewstudents.jsp in an iframe. 

Re-write this functionality with Angular.

Don't allow teacher to put multiple students in workgroup if maxStudents is set to 1.

Designs: https://balsamiq.cloud/s8brvqj/p9j1not/rDB2A.

**Comment by breity** [comment]
Duplicate issue. Closed by #315.
