### ISSUE TITLE
Manage students: period select dropdown updating issues

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Client#271]
### Description
The period select drop down has these issues related to the new manage students tool

**Period select does not update number of teams**
1. Move a team to another period.
2. The period select does not update the number of teams in each period.

**Can't view team that is moved to empty period**
1. Move a team to another period that has no teams.
2. You will not be able to view the period that the team was moved to because the period drop down still thinks there are 0 teams in that period.
3. The team and students in the team will no longer appear anywhere even if you refresh the page.

**Comment by breity** [comment]
Closed by #272.
