### ISSUE TITLE
Manage Students: Create Team and Unassigned Students

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Client#308]
## Unassigned Students
Allow the teacher to see unassigned students and move students from unassigned to an existing team, and vise-versa. Show a warning dialog about students losing data when they are moved between teams.

<img width="368" alt="Screen Shot 2021-08-27 at 9 48 28 AM" src="https://user-images.githubusercontent.com/119416/131161771-09cd1bdc-02bc-4609-a6b6-00cb1b363fbd.png">

## Create Team
Add a button to allow the teacher to create a new team. This should open a dialog where they can see all the students in the period, and select up to 3 students to add to the new team. If the student is already in an existing team, show the warning dialog (see above). Upon successful creation of the new team, the dialog should close and the manage students page should update with the new team.

<img width="373" alt="Screen Shot 2021-08-27 at 9 48 42 AM" src="https://user-images.githubusercontent.com/119416/131162012-232cdf8e-25de-45dc-a379-e23b0cd4a8fc.png">

**Comment by breity** [comment]
Closed by #309.
