### ISSUE TITLE
Create view for manually assigning peer groups

### ISSUE THREAD

**Issue by geoffreykwan** [WISE-Community/WISE-Client#407]
The view should be opened in a popup from a button in the Peer Chat step grading view.

It should
- show all the groups
- show all unassigned workgroups
- allow creating a new group
- allow dragging and dropping workgroups into a different group

Here is a mockup of what it should roughly look like.
https://balsamiq.cloud/s8brvqj/p9j1not/r2370

**Comment by breity** [comment]
Closed by #408.
