### ISSUE TITLE
Peer Chat: Change notification message to remove names

### ISSUE THREAD

**Issue by hirokiterashima** [WISE-Community/WISE-Client#549]
### Description

For notifications about new messages received in the Peer Chat component, change the message to remove names and make it more generic: “You have new replies”, or something of the sort

<img width="543" alt="Screen Shot 2022-03-17 at 9 55 33 AM" src="https://user-images.githubusercontent.com/119416/158853508-a710c525-eb74-422c-8224-4bffbc20113e.png">

This will make it generic enough to work for one or more students/messages, and also mask who sent the replies (aggregating notification and showing a list of students in one messages is a bit difficult atm)

**Comment by breity** [comment]
Closed by #553.
